[tool.poetry]
name = "yield-ai-service"
version = "0.1.0"
description = "Microservice IA"
authors = ["Ton Nom <email@example.com>"]
readme = "README.md"
packages = [{ include = "*.py" }]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.13"
fastapi = "^0.115.0"
uvicorn = "^0.34.0"
numpy = "^2.2.0"
scikit-learn = "^1.6.0"
pandas = "^2.2.0"
joblib = "^1.4.0"
lightgbm = "^4.5.0"
pymongo = "^4.10.0"
motor = "^3.6.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-asyncio = "^0.24.0"

[tool.poetry.scripts]
# Cette ligne permet de taper "poetry run start" pour lancer ton API
start = "main:run_server"
# Cette ligne permet de taper "poetry run report" pour lancer tes tests de performance
report = "pytest:main"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"