apiVersion: apps/v1
kind: Deployment
metadata:
  name: yield-ai-python-deploy
  labels:
    app: yield-ai-python
spec:
  replicas: 1 # On commence avec un seul exemplaire
  selector:
    matchLabels:
      app: yield-ai-python
  template:
    metadata:
      labels:
        app: yield-ai-python
    spec:
      containers:
        - name: python-ai
          image: yassinezadod/yield-ai-python:latest # Ton image Docker Hub !
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-service:27017" # Nom interne à K8s
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: yield-ai-python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Service interne
